### ISSUE TITLE
ChocolateyCeneralManagement App not starting after upgrading to version 0.6.2

### ISSUE THREAD

**Issue by 2Deep2Dive** [chocolatey/chocolatey-licensed-issues#257]
### What You Are Seeing?
AN error regarding invalid Base-64 string
### What is Expected?
The web application to start successfully
### How Did You Get This To Happen? (Steps to Reproduce)
Followed all upgrade steps as mentioned in the documentation, the upgrade was smooth with no errors until attempting to access the web portal, HTTP Error 500.30 - ANCM In-Process Start Failure was received 
### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
Application: ChocolateySoftware.ChocolateyManagement.Web.Mvc.exe
CoreCLR Version: 4.700.21.35901
.NET Core Version: 3.1.18
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Abp.Runtime.Security.SimpleStringCipher.Decrypt(String cipherText, String passPhrase, Byte[] salt, Nullable`1 keySize, Byte[] initVectorBytes)
   at Abp.Configuration.SettingEncryptionService.Decrypt(SettingDefinition settingDefinition, String encryptedValue)
   at Abp.Configuration.SettingManager.ConvertSettingInfosToDictionary(List`1 settingValues)
   at Abp.Configuration.SettingManager.<>c__DisplayClass70_0.<GetTenantSettingsFromCache>b__0()
   at Abp.Runtime.Caching.TypedCacheExtensions.<>c__DisplayClass0_0`2.<Get>b__0(TKey k)
   at Abp.Runtime.Caching.TypedCacheWrapper`2.<>c__DisplayClass16_0.<Get>b__0(String k)
   at Abp.Runtime.Caching.AbpCacheBase`2.Get(TKey key, Func`2 factory)
   at Abp.Runtime.Caching.TypedCacheWrapper`2.Get(TKey key, Func`2 factory)
   at Abp.Runtime.Caching.TypedCacheExtensions.Get[TKey,TValue](ITypedCache`2 cache, TKey key, Func`1 factory)
   at Abp.Configuration.SettingManager.GetTenantSettingsFromCache(Int32 tenantId)
   at Abp.Configuration.SettingManager.GetReadOnlyTenantSettings(Int32 tenantId)
   at Abp.Configuration.SettingManager.GetSettingValueForTenantOrNull(Int32 tenantId, String name)
   at Abp.Configuration.SettingManager.GetSettingValueInternal(String name, Nullable`1 tenantId, Nullable`1 userId, Boolean fallbackToDefault)
   at Abp.Configuration.SettingManager.GetSettingValue(String name)
   at Castle.Proxies.SettingManagerProxy.GetSettingValue_callback(String name)
   at Castle.Proxies.Invocations.ISettingManager_GetSettingValue.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Abp.Domain.Uow.UnitOfWorkInterceptor.InterceptSynchronous(IInvocation invocation)
   at Castle.DynamicProxy.AsyncDeterminationInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.SettingManagerProxy.GetSettingValue(String name)
   at Abp.Configuration.SettingManagerExtensions.GetSettingValue[T](ISettingManager settingManager, String name)
   at ChocolateySoftware.ChocolateyManagement.Web.Startup.ChocolateyManagementWebMvcModule.PostInitialize()
   at Abp.Modules.AbpModuleManager.<>c.<StartModules>b__15_2(AbpModuleInfo module)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Abp.Modules.AbpModuleManager.StartModules()
   at Abp.AbpBootstrapper.Initialize()
   at Abp.AspNetCore.AbpApplicationBuilderExtensions.InitializeAbp(IApplicationBuilder app)
   at Abp.AspNetCore.AbpApplicationBuilderExtensions.UseAbp(IApplicationBuilder app, Action`1 optionsAction)
   at ChocolateySoftware.ChocolateyManagement.Web.Startup.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at ChocolateySoftware.ChocolateyManagement.Web.Startup.Program.Main(String[] args)

~~~

</p>

</details>

**Comment by pauby** [comment]
@2Deep2Dive Have you raised a support ticket for this? If not, run `choco support` to find your options.

**Comment by 2Deep2Dive** [comment]
@pauby Thank you for the prompt respond,  I haven't opened a ticket yet, but will send the issue by email with the log file tomorrow and I will post the results back here depending if it is really a bug or just a misconfiguration

**Comment by ryanrichter94** [comment]
I'll go ahead and close this GitHub issue. If you are still experiencing issues with CCM please run `choco support` on a machine with Chocolatey installed to find ways of reaching out to us.
