### ISSUE TITLE
chocolateygui 1.1.2 crashes on launch with chocolateygui.extension installed

### ISSUE THREAD

**Issue by istewart-qub** [chocolatey/chocolatey-licensed-issues#338]
### Checklist
* [x] I have verified this is the correct repository for opening this issue.
* [x] I have verified no other issues exist related to my problem.
* [x] I have verified this is not an issue for a specific package.
* [x] I have verified this issue is not security related.

### What You Are Seeing?
The current version of chocolateygui.extension ( v1.0.1 ) does not appear to be compatible with the recently released version of chocolatey gui ( v1.1.2).  When trying to launch the application crashes with a message stating that it can't load the assembly for litedb v5.0.5.  According to https://github.com/chocolatey/ChocolateyGUI/issues/985 this assembly was updated to 5.0.15 in chocolatey gui v.1.1.2.  Either uninstalling chocolateygui.extension or downgrading chocolatey gui to v.1.1.1 will allow the application to launch.

The error message is as follows:

Failed to start application.\nAn error occurred during the activation of a particular registration. See the inner exception for details.
Registration: Activator = ChocolateyService (ReflectionActivator),
Services = [ChocolateyGui.Common.Services.IChocolateyService],
Lifetime = Autofac.Core.Lifetime. RootScopeLifetime, Sharing = Shared,
Ownership = OwnedByLifetimeScope ---> Could not load file or
assembly 'LiteDB, Version=5.0.5.0, Culture=neutral, PublicKeyToken=4ee40123013c927' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) (See inner exception for details.)n\nMore details available in application logs.

### What is Expected?
chocolatey gui launches, and has all business features enabled.

### How Did You Get This To Happen?
1. choco install chocolateygui --version 1.1.1

- - -
Chocolatey v1.3.0 Business
Installing the following packages:
chocolateygui
By installing, you accept licenses for the packages.
Progress: Downloading ChocolateyGUI 1.1.1... 100%

ChocolateyGUI v1.1.1 [Approved]
chocolateygui package files install completed. Performing other installation steps.
Installing ChocolateyGUI.msi...
ChocolateyGUI.msi has been installed.
Added C:\ProgramData\chocolatey\bin\chocolateygui.exe shim pointed to 'c:\program files (x86)\chocolatey gui\chocolateygui.exe'.
Added C:\ProgramData\chocolatey\bin\chocolateyguicli.exe shim pointed to 'c:\program files (x86)\chocolatey gui\chocolateyguicli.exe'.
  chocolateygui may be able to be automatically uninstalled.
 The install of chocolateygui was successful.
  Software install location not explicitly set, it could be in package or
  default install location of installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**[Application runs as expected. Chocolatey Gui v1.1.1.0 is diplayed in the bottom left corner of the window.]**

- - -
1. choco install chocolateygui.extension

- - -
Chocolatey v1.3.0 Business
Installing the following packages:
chocolateygui.extension
By installing, you accept licenses for the packages.
Progress: Downloading chocolateygui.extension 1.0.1... 100%

chocolateygui.extension v1.0.1
chocolateygui.extension package files install completed. Performing other installation steps.
 Installed/updated chocolateygui extensions.
Directory 'C:\ProgramData\chocolatey\lib\chocolateygui.extension\tools' does not exist.
Directory 'C:\ProgramData\chocolatey\lib\chocolateygui.extension\tools' does not exist.
 The install of chocolateygui.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolateygui'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**[Application runs as expected. Chocolatey GUI v1.1.1.0 Business is displayed in bottom left of the window.]**

- - -
## 3. choco install chocolateygui --version 1.1.2
Chocolatey v1.3.0 Business
Installing the following packages:
chocolateygui
By installing, you accept licenses for the packages.
Progress: Downloading ChocolateyGUI 1.1.2... 100%

ChocolateyGUI v1.1.2 [Approved]
chocolateygui package files install completed. Performing other installation steps.
Installing ChocolateyGUI.msi...
ChocolateyGUI.msi has been installed.
Added C:\ProgramData\chocolatey\bin\chocolateygui.exe shim pointed to 'c:\program files (x86)\chocolatey gui\chocolateygui.exe'.
Added C:\ProgramData\chocolatey\bin\chocolateyguicli.exe shim pointed to 'c:\program files (x86)\chocolatey gui\chocolateyguicli.exe'.
  chocolateygui may be able to be automatically uninstalled.
 The install of chocolateygui was successful.
  Software install location not explicitly set, it could be in package or
  default install location of installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**[Application crashes on launch.]**

- - -
## 4. choco uninstall chocolateygui.extension
Chocolatey v1.3.0 Business
Uninstalling the following packages:
chocolateygui.extension

chocolateygui.extension v1.0.1
 Skipping auto uninstaller - No registry snapshot.
 Uninstalled chocolateygui extensions.
 chocolateygui.extension has been successfully uninstalled.

Chocolatey uninstalled 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**[Application runs as expected. Chocolatey Gui v1.1.2.0 shown in bottom left of the window.]**

### System Details
* Operating System: 10.0.19044.0
* Windows PowerShell version: 5.1.19041.2364
* Chocolatey CLI Version: 1.3.0
* Chocolatey Licensed Extension version: chocolatey.extension 5.0.1
* Chocolatey License type: Business
* Terminal/Emulator: Microsoft Terminal

### Installed Packages
```bash
N/A
```

### Output Log
```bash
Contents of the chocolateygui log file are below.  I have redacted the url to our internal package repo.

---

2023-03-09 14:53:23.070 +00:00 [Information] Branding assembly already exists, nothing else to be done
2023-03-09 14:54:18.137 +00:00 [Fatal] Failed to start application.
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ChocolateyService (ReflectionActivator), Services = [ChocolateyGui.Common.Services.IChocolateyService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Could not load file or assembly 'LiteDB, Version=5.0.5.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) (See inner exception for details.) ---> System.IO.FileLoadException: Could not load file or assembly 'LiteDB, Version=5.0.5.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at ChocolateyGui.Licensed.ChocolateyGuiLicensedModule..(Object , ActivatingEventArgs`1 )
   at Autofac.Core.Registration.ComponentRegistration.RaiseActivating(IComponentContext context, IEnumerable`1 parameters, Object& instance)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at ChocolateyGui.Common.Windows.Bootstrapper.<OnStartup>d__43.MoveNext() in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\Bootstrapper.cs:line 123
2023-03-09 14:55:33.726 +00:00 [Information] Branding assembly already exists, nothing else to be done
2023-03-09 14:56:06.577 +00:00 [Fatal] Failed to start application.
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ChocolateyService (ReflectionActivator), Services = [ChocolateyGui.Common.Services.IChocolateyService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Could not load file or assembly 'LiteDB, Version=5.0.5.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) (See inner exception for details.) ---> System.IO.FileLoadException: Could not load file or assembly 'LiteDB, Version=5.0.5.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at ChocolateyGui.Licensed.ChocolateyGuiLicensedModule..(Object , ActivatingEventArgs`1 )
   at Autofac.Core.Registration.ComponentRegistration.RaiseActivating(IComponentContext context, IEnumerable`1 parameters, Object& instance)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at ChocolateyGui.Common.Windows.Bootstrapper.<OnStartup>d__43.MoveNext() in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\Bootstrapper.cs:line 123
2023-03-09 14:59:31.220 +00:00 [Information] QUB software - <redacted> (Authenticated)| Priority 0|Bypass Proxy - False|Self-Service - True|Admin Only - False.
2023-03-09 14:59:31.244 +00:00 [Information] admins only - https://chocolatey.org/api/v2/ | Priority 5|Bypass Proxy - False|Self-Service - False|Admin Only - True.
2023-03-09 14:59:31.261 +00:00 [Information] chocolatey.licensed [Disabled] - https://licensedpackages.chocolatey.org/api/v2/ (Authenticated)| Priority 10|Bypass Proxy - False|Self-Service - False|Admin Only - False.
2023-03-09 14:59:36.859 +00:00 [Warning] Some packages specified in the 'except' list were not found in the local packages: 'chocolateygui.extension,chocolateygui-branding,inkscape,r.project,r.studio,anaconda3,bonjour,skype,teamviewer,teamviewer.host,teamviewer-qs,microsoft-windows-terminal,adobe-creative-cloud,microsoft-teams.install,rtools'
2023-03-09 14:59:36.861 +00:00 [Information] These packages will not be upgraded because they were specified in the 'except' list: chocolatey,chocolatey-license,chocolatey.extension,chocolatey-agent,chocolateygui,PSWindowsUpdate
2023-03-09 14:59:39.726 +00:00 [Information] anaconda3-python|2021.11|2021.11|false
2023-03-09 14:59:41.905 +00:00 [Information] cloud-latex|0.0.0.0|0.0.0.0|false
2023-03-09 14:59:42.010 +00:00 [Information] dell-command-update-for-windows-universal|4.7.0|4.7.0|false
2023-03-09 14:59:42.100 +00:00 [Information] dell-supportassist-os-recovery-plugin-for-dell-update|5.5.1.16143|5.5.1.16143|false
2023-03-09 14:59:45.885 +00:00 [Information] intelr-management-engine-components|2141.15.0.2511|2141.15.0.2511|false
2023-03-09 14:59:47.038 +00:00 [Information] lithnet-idle-logoff-utility|1.2.8134.23029|1.2.8134.23029|false
2023-03-09 14:59:47.121 +00:00 [Information] local-administrator-password-solution|6.2.0.0|6.2.0.0|false
2023-03-09 14:59:47.205 +00:00 [Information] microsoft-edge-webview2-runtime|98.0.1108.62|98.0.1108.62|false
2023-03-09 14:59:47.343 +00:00 [Information] microsoft-onedrive|21.30.211.2|21.30.211.2|false
2023-03-09 14:59:47.447 +00:00 [Information] microsoft-search-in-bing|2.0.2|2.0.2|false
2023-03-09 14:59:47.641 +00:00 [Information] microsoft-update-health-tools|2.93.0.0|2.93.0.0|false
2023-03-09 14:59:47.731 +00:00 [Information] microsoft-visual-cplusplus-redistributable|14.31.31103.0|14.31.31103.0|false
2023-03-09 14:59:47.954 +00:00 [Information] microsoft-windows-desktop-runtime|5.0.14.30911|5.0.14.30911|false
2023-03-09 14:59:48.041 +00:00 [Information] mozilla-firefox-en-gb|97.0.1|97.0.1|false
2023-03-09 14:59:48.123 +00:00 [Information] mozilla-maintenance-service|97.0|97.0|false
2023-03-09 14:59:49.416 +00:00 [Information] osirium-pam-client|7.5.2|7.5.2|false
2023-03-09 14:59:49.605 +00:00 [Information] powershell-7|7.2.0.0|7.2.0.0|false
2023-03-09 14:59:50.837 +00:00 [Information] system.data.sqlite-release|1.0.110.0|1.0.110.0|false
2023-03-09 15:12:48.264 +00:00 [Information] QUB software - <redacted>(Authenticated)| Priority 0|Bypass Proxy - False|Self-Service - True|Admin Only - False.
2023-03-09 15:12:48.289 +00:00 [Information] admins only - https://chocolatey.org/api/v2/ | Priority 5|Bypass Proxy - False|Self-Service - False|Admin Only - True.
2023-03-09 15:12:48.308 +00:00 [Information] chocolatey.licensed [Disabled] - https://licensedpackages.chocolatey.org/api/v2/ (Authenticated)| Priority 10|Bypass Proxy - False|Self-Service - False|Admin Only - False.
2023-03-09 15:12:53.978 +00:00 [Warning] Some packages specified in the 'except' list were not found in the local packages: 'inkscape,r.project,r.studio,anaconda3,bonjour,skype,teamviewer,teamviewer.host,teamviewer-qs,microsoft-windows-terminal,adobe-creative-cloud,microsoft-teams.install,rtools'
2023-03-09 15:12:53.980 +00:00 [Information] These packages will not be upgraded because they were specified in the 'except' list: chocolatey,chocolatey-license,chocolatey.extension,chocolatey-agent,chocolateygui,chocolateygui.extension,chocolateygui-branding,PSWindowsUpdate
2023-03-09 15:24:07.422 +00:00 [Information] QUB software - <redacted> (Authenticated)| Priority 0|Bypass Proxy - False|Self-Service - True|Admin Only - False.
2023-03-09 15:24:07.445 +00:00 [Information] admins only - https://chocolatey.org/api/v2/ | Priority 5|Bypass Proxy - False|Self-Service - False|Admin Only - True.
2023-03-09 15:24:07.462 +00:00 [Information] chocolatey.licensed [Disabled] - https://licensedpackages.chocolatey.org/api/v2/ (Authenticated)| Priority 10|Bypass Proxy - False|Self-Service - False|Admin Only - False.
2023-03-09 15:24:12.969 +00:00 [Warning] Some packages specified in the 'except' list were not found in the local packages: 'chocolateygui.extension,chocolateygui-branding,inkscape,r.project,r.studio,anaconda3,bonjour,skype,teamviewer,teamviewer.host,teamviewer-qs,microsoft-windows-terminal,adobe-creative-cloud,microsoft-teams.install,rtools'
2023-03-09 15:24:12.977 +00:00 [Information] These packages will not be upgraded because they were specified in the 'except' list: chocolatey,chocolatey-license,chocolatey.extension,chocolatey-agent,chocolateygui,PSWindowsUpdate
2023-03-09 15:24:16.012 +00:00 [Information] anaconda3-python|2021.11|2021.11|false
2023-03-09 15:24:17.070 +00:00 [Information] cloud-latex|0.0.0.0|0.0.0.0|false
2023-03-09 15:24:17.160 +00:00 [Information] dell-command-update-for-windows-universal|4.7.0|4.7.0|false
2023-03-09 15:24:17.259 +00:00 [Information] dell-supportassist-os-recovery-plugin-for-dell-update|5.5.1.16143|5.5.1.16143|false
2023-03-09 15:25:28.604 +00:00 [Information] QUB software - <redacted> (Authenticated)| Priority 0|Bypass Proxy - False|Self-Service - True|Admin Only - False.
2023-03-09 15:25:28.628 +00:00 [Information] admins only - https://chocolatey.org/api/v2/ | Priority 5|Bypass Proxy - False|Self-Service - False|Admin Only - True.
2023-03-09 15:25:28.647 +00:00 [Information] chocolatey.licensed [Disabled] - https://licensedpackages.chocolatey.org/api/v2/ (Authenticated)| Priority 10|Bypass Proxy - False|Self-Service - False|Admin Only - False.
2023-03-09 15:25:30.768 +00:00 [Warning] Some packages specified in the 'except' list were not found in the local packages: 'chocolateygui.extension,chocolateygui-branding,inkscape,r.project,r.studio,anaconda3,bonjour,skype,teamviewer,teamviewer.host,teamviewer-qs,microsoft-windows-terminal,adobe-creative-cloud,microsoft-teams.install,rtools'
2023-03-09 15:25:30.770 +00:00 [Information] These packages will not be upgraded because they were specified in the 'except' list: chocolatey,chocolatey-license,chocolatey.extension,chocolatey-agent,chocolateygui,PSWindowsUpdate
2023-03-09 15:25:32.243 +00:00 [Information] anaconda3-python|2021.11|2021.11|false
2023-03-09 15:25:33.700 +00:00 [Information] cloud-latex|0.0.0.0|0.0.0.0|false
2023-03-09 15:25:33.786 +00:00 [Information] dell-command-update-for-windows-universal|4.7.0|4.7.0|false
2023-03-09 15:25:33.857 +00:00 [Information] dell-supportassist-os-recovery-plugin-for-dell-update|5.5.1.16143|5.5.1.16143|false
2023-03-09 15:25:35.237 +00:00 [Information] intelr-management-engine-components|2141.15.0.2511|2141.15.0.2511|false
2023-03-09 15:25:35.854 +00:00 [Information] lithnet-idle-logoff-utility|1.2.8134.23029|1.2.8134.23029|false
2023-03-09 15:25:35.948 +00:00 [Information] local-administrator-password-solution|6.2.0.0|6.2.0.0|false
2023-03-09 15:25:36.037 +00:00 [Information] microsoft-edge-webview2-runtime|98.0.1108.62|98.0.1108.62|false
2023-03-09 15:25:36.119 +00:00 [Information] microsoft-onedrive|21.30.211.2|21.30.211.2|false
2023-03-09 15:25:36.200 +00:00 [Information] microsoft-search-in-bing|2.0.2|2.0.2|false
2023-03-09 15:25:36.373 +00:00 [Information] microsoft-update-health-tools|2.93.0.0|2.93.0.0|false
2023-03-09 15:25:36.907 +00:00 [Information] microsoft-visual-cplusplus-redistributable|14.31.31103.0|14.31.31103.0|false
2023-03-09 15:25:37.014 +00:00 [Information] microsoft-windows-desktop-runtime|5.0.14.30911|5.0.14.30911|false
2023-03-09 15:25:37.105 +00:00 [Information] mozilla-firefox-en-gb|97.0.1|97.0.1|false
2023-03-09 15:25:37.335 +00:00 [Information] mozilla-maintenance-service|97.0|97.0|false
2023-03-09 15:25:38.470 +00:00 [Information] osirium-pam-client|7.5.2|7.5.2|false
2023-03-09 15:25:38.645 +00:00 [Information] powershell-7|7.2.0.0|7.2.0.0|false
2023-03-09 15:25:39.725 +00:00 [Information] system.data.sqlite-release|1.0.110.0|1.0.110.0|false
2023-03-09 15:25:41.124 +00:00 [Information] windows-subsystem-for-linux-update|5.10.60.1|5.10.60.1|false
2023-03-09 15:26:40.206 +00:00 [Information] No branding files exist, nothing else to be done
2023-03-09 15:27:42.707 +00:00 [Fatal] Failed to start application.
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ChocolateyService (ReflectionActivator), Services = [ChocolateyGui.Common.Services.IChocolateyService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Could not load file or assembly 'LiteDB, Version=5.0.5.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) (See inner exception for details.) ---> System.IO.FileLoadException: Could not load file or assembly 'LiteDB, Version=5.0.5.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at ChocolateyGui.Licensed.ChocolateyGuiLicensedModule..(Object , ActivatingEventArgs`1 )
   at Autofac.Core.Registration.ComponentRegistration.RaiseActivating(IComponentContext context, IEnumerable`1 parameters, Object& instance)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at ChocolateyGui.Common.Windows.Bootstrapper.<OnStartup>d__43.MoveNext() in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\Bootstrapper.cs:line 123
2023-03-09 15:29:49.949 +00:00 [Information] No branding files exist, nothing else to be done
2023-03-09 15:29:51.741 +00:00 [Fatal] Failed to start application.
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ChocolateyService (ReflectionActivator), Services = [ChocolateyGui.Common.Services.IChocolateyService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Could not load file or assembly 'LiteDB, Version=5.0.5.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) (See inner exception for details.) ---> System.IO.FileLoadException: Could not load file or assembly 'LiteDB, Version=5.0.5.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at ChocolateyGui.Licensed.ChocolateyGuiLicensedModule..(Object , ActivatingEventArgs`1 )
   at Autofac.Core.Registration.ComponentRegistration.RaiseActivating(IComponentContext context, IEnumerable`1 parameters, Object& instance)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at ChocolateyGui.Common.Windows.Bootstrapper.<OnStartup>d__43.MoveNext() in C:\buildAgent\work\774e9aed9020e028\Source\ChocolateyGui.Common.Windows\Bootstrapper.cs:line 123
2023-03-09 15:31:51.738 +00:00 [Information] QUB software - <redacted> (Authenticated)| Priority 0|Bypass Proxy - False|Self-Service - True|Admin Only - False.
2023-03-09 15:31:51.763 +00:00 [Information] admins only - https://chocolatey.org/api/v2/ | Priority 5|Bypass Proxy - False|Self-Service - False|Admin Only - True.
2023-03-09 15:31:51.780 +00:00 [Information] chocolatey.licensed [Disabled] - https://licensedpackages.chocolatey.org/api/v2/ (Authenticated)| Priority 10|Bypass Proxy - False|Self-Service - False|Admin Only - False.
2023-03-09 15:33:33.664 +00:00 [Information] No branding files exist, nothing else to be done
2023-03-09 15:33:34.816 +00:00 [Information] QUB software - <redacted> (Authenticated)| Priority 0|Bypass Proxy - False|Self-Service - True|Admin Only - False.
2023-03-09 15:33:34.836 +00:00 [Information] admins only - https://chocolatey.org/api/v2/ | Priority 5|Bypass Proxy - False|Self-Service - False|Admin Only - True.
2023-03-09 15:33:34.853 +00:00 [Information] chocolatey.licensed [Disabled] - https://licensedpackages.chocolatey.org/api/v2/ (Authenticated)| Priority 10|Bypass Proxy - False|Self-Service - False|Admin Only - False.
2023-03-09 15:34:24.647 +00:00 [Information] No branding files exist, nothing else to be done
2023-03-09 15:34:25.815 +00:00 [Information] QUB software - <redacted> (Authenticated)| Priority 0|Bypass Proxy - False|Self-Service - True|Admin Only - False.
2023-03-09 15:34:25.836 +00:00 [Information] admins only - https://chocolatey.org/api/v2/ | Priority 5|Bypass Proxy - False|Self-Service - False|Admin Only - True.
2023-03-09 15:34:25.853 +00:00 [Information] chocolatey.licensed [Disabled] - https://licensedpackages.chocolatey.org/api/v2/ (Authenticated)| Priority 10|Bypass Proxy - False|Self-Service - False|Admin Only - False.
```

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/chocolateygui-licensed/-/issues/36) by [Unito](https://www.unito.io)
┆Milestone: 1.0.2

**Comment by pauby** [comment]
Thanks for reporting this @istewart-qub. We are working on a new release of Chocolatey GUI Licensed Extension now.
